name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Manual Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Install dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci --ignore-scripts
          else
            npm install --ignore-scripts --no-package-lock
          fi
      
      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.version }} -m "chore(release): %s"
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      
      - name: Push changes
        run: |
          git push
          git push --tags
      
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_VERSION }}
          release_name: Release v${{ env.NEW_VERSION }}
          body: |
            ## Changes in this Release
            
            See [CHANGELOG.md](https://github.com/tobias-schuemann/claude-frontend/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false